### ISSUE TITLE
Como adicionar uma nova RF? 

### ISSUE THREAD

**Issue by danilodene** [fernac03/JFL_ACTIVE#2]
Estou com uma central JFL Active full 32, ao adicionar uma zona adicionei serial do sensor mas não atualizou o status 
![anexo_10676](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/b7058808-f0ba-44be-b132-fc710a66c29d)
![anexo_10677](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/b40efa4b-d922-4232-9490-bce182ba7d72)

Conseguiria me ajudar?

**Comment by fernac03** [comment]
O protocolo disponibilizado pela  JFL não envia  os  dados  da  RF  apenas  da Zona, então cadastre  como um sensor  de porta  e coloque  a zona correta  que  ira  funcionar

**Comment by danilodene** [comment]
Bom dia Fernac03, muito obrigado pela ajuda. 

Seria conforme mostra abaixo?

![image](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/b8088712-522b-4bad-9096-c388225b673c)

Fica sempre fechado, mesmo no app mostrando aberto 

![image](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/3a97bca6-78a2-48c5-884f-5631ab098916)


O que será que pode ser? 

Grato

**Comment by danilodene** [comment]
boa noite, alguma @fernac03  o que você acha que poderia ser?

**Comment by fernac03** [comment]
qual a  zona  esta  configurado na  JFL   tem que  ser  a  mesma no print  que  voce  enviou anterior  foi a zona  5  neste novo print  foi a zona  8 , tem que  ser exatamente  a  mesma  zona

**Comment by danilodene** [comment]
Bom dia, segue novos prints 
![anexo_10743](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/ed57b6b1-73f7-4995-9c33-c5431f54659c)
![IMG-20230522-WA0001](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/f3119c49-b2c5-4fc1-98b2-e70dc6cfd2ed)
![IMG-20230522-WA0002](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/52a77c27-12ce-4705-9fa9-0234a35bf0ab)
![IMG-20230522-WA0003](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/44aa7cb1-7fb1-480e-ad04-7e5c078789e1)
![IMG-20230522-WA0004](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/ab6511f3-b3f2-4e33-bfcc-16da6a397ccd)
![IMG-20230522-WA0005](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/5f32ccfb-fcb6-41f9-98b8-cd78c8a061d8)

**Comment by danilodene** [comment]
Obs: armar e desarmar está funcionando certinho, apenas o monitoramento das zonas que não

**Comment by fernac03** [comment]
as zonas  com fio estão reportando corretamente ?

**Comment by danilodene** [comment]
Quando fecho e abro a zona no app fica certo tipo mostra nele que está aberto e fechado. Seria isso a pergunta?

**Comment by fernac03** [comment]
a titulo de teste,  substitua  o  __init__.py  na pasta \config\custom_components\jfl_active  do seu home assistant  por  o que acabei de subir  no  repositorio principal .
ele  ira  gerar  alguns  logs  a mais  do pedido de status da  central  para  ver  se  esta recebendo os pacotes corretos  da  central.
apos  substituir  reinicie  seu home assistant

**Comment by danilodene** [comment]
@fernac03  Fiz a troca do arquivo, uma dúvida, ele vai aparecer em qual arquivo de log? 
![image](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/a1011848-9c3f-41e5-b03d-462be09724bf)
![image](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/0ea67e4c-2928-40f4-ada6-bc3d67138f52)

**Comment by fernac03** [comment]
so filtrar  por  jfl
deve  aparecer

algo assim
2023-05-22 09:21:46.138 WARNING (Thread-5) [custom_components.jfl_active]
Envia pedido de status apos tempo
2023-05-22 09:21:46.886 WARNING (Thread-5) [custom_components.jfl_active]
tamanho do Pacote 57
2023-05-22 09:22:47.168 WARNING (Thread-5) [custom_components.jfl_active]
tamanho do Pacote 5
2023-05-22 09:22:47.169 WARNING (Thread-5) [custom_components.jfl_active]
Envia pedido de status apos tempo
2023-05-22 09:22:48.395 WARNING (Thread-5) [custom_components.jfl_active]
tamanho do Pacote 57
2023-05-22 09:23:47.997 WARNING (Thread-5) [custom_components.jfl_active]
tamanho do Pacote 5
2023-05-22 09:23:47.998 WARNING (Thread-5) [custom_components.jfl_active]
Envia pedido de status apos tempo
2023-05-22 09:23:49.233 WARNING (Thread-5) [custom_components.jfl_active]
tamanho do Pacote 57
2023-05-22 09:24:49.021 WARNING (Thread-5) [custom_components.jfl_active]
tamanho do Pacote 5
2023-05-22 09:24:49.022 WARNING (Thread-5) [custom_components.jfl_active]
Envia pedido de status apos tempo
2023-05-22 09:24:50.173 WARNING (Thread-5) [custom_components.jfl_active]
tamanho do Pacote 57
2023-05-22 09:25:50.056 WARNING (Thread-5) [custom_components.jfl_active]
tamanho do Pacote 5

Em seg., 22 de mai. de 2023 às 11:57, Danilo Dene ***@***.***>
escreveu:

**Comment by danilodene** [comment]
no print acima já havia filtrado JFL, no entanto nada relevante 

Abaixo o log do journalctl, nada também, 
![image](https://github.com/fernac03/JFL_ACTIVE/assets/5453097/1d5e7ee3-9518-4a15-a829-3ae06c5cf040)

**Comment by fernac03** [comment]
voce reiniciou o Home assistant ?  nos seus log  não apareceu a  conexao da  central

**Comment by danilodene** [comment]
vishi, umas 10 vezes rsrsrs. Então muito esquisito

**Comment by fernac03** [comment]
muito extranho  deveria  uns  logs  escrito "tamanho do pacote"

**Comment by danilodene** [comment]
O esquisito que funciona o armar e desarmar. A minha central é a JFL Active full 32, tem alguma diferença ?

**Comment by fernac03** [comment]
boa tarde,
o protocolo de comunicação  da JFL  tem suporte  para
[image: image.png]
tem um outro usuario   tendo problemas  com a  Active100 bus , basicamente
o mesmo problema  que voce , porem  na  dele  aparece os  logs  que  a
central esta enviando o report  so os  dados  que não estão vindo corretos
, estou em contato com a JFL  para  tentar  resolver,
uma  pergunta , o report  da  sua  central  esta  em primeiro  o ethernet  ?


Em ter., 23 de mai. de 2023 às 09:44, Danilo Dene ***@***.***>
escreveu:

**Comment by danilodene** [comment]
@fernac03  muito obrigado pela ajuda. Sobre a prioridade está sim primeiro pela ethernet.

Obrigado

**Comment by fernac03** [comment]
fiz  umas  atualizações  no __init__.py   atualiza  o seu ai   e  teste  por  favor creio  que esta resolvido

**Comment by danilodene** [comment]
Fala Fernando, muito obrigado pelo retorno, fiz o teste por aqui ainda não está rolando. 

Segue o log: 

2023-06-13 14:28:54.702 WARNING (Thread-2) [custom_components.jfl_active] Starting JFL Integration
2023-06-13 14:29:23.887 WARNING (Thread-2) [custom_components.jfl_active] Connected by ('192.168.2.1', 55698)
2023-06-13 14:29:24.067 WARNING (Thread-2) [custom_components.jfl_active] tamanho do Pacote 102
2023-06-13 14:29:24.069 WARNING (Thread-2) [custom_components.jfl_active] Tipo Central  A6
2023-06-13 14:29:24.076 WARNING (Thread-2) [custom_components.jfl_active] Problema da central  01
2023-06-13 14:29:24.080 WARNING (Thread-2) [custom_components.jfl_active] Total de particoes  01
2023-06-13 14:29:24.082 WARNING (Thread-2) [custom_components.jfl_active] ###############  PART False 
2023-06-13 14:29:24.085 WARNING (Thread-2) [custom_components.jfl_active] pacote com 102 Eletrificador   00
2023-06-13 14:29:24.097 WARNING (Thread-2) [custom_components.jfl_active] Envia pedido de Status
2023-06-13 14:29:24.577 WARNING (Thread-2) [custom_components.jfl_active] tamanho do Pacote 126
2023-06-13 14:29:24.578 INFO (Thread-2) [custom_components.jfl_active] pacote maior que 118 b'{~\x01M4B\x13\x06#\x14)$d\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00x\x88\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x1b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00B'

**Comment by fernac03** [comment]
bom dia, extranho  o pacote  de dados  recebido  esta com o tamanho correto mas  todos  os dados  dos sensores  estao zerados muito extranho

**Comment by fernac03** [comment]
bom dia  podemos  marcar  sim  ,

Em ter., 13 de jun. de 2023 às 14:24, Danilo Dene ***@***.***>
escreveu:

**Comment by danilodene** [comment]
uma dúvida, você teria a documentação do protocolo? 
muito obrigado

**Comment by fernac03** [comment]
tenho mas  com  o acordo  de confidencialidade  que  fiz com a JFL  não
posso  compartilhar.

Em qua., 14 de jun. de 2023 às 10:18, Danilo Dene ***@***.***>
escreveu:

**Comment by ITMPGIT** [comment]
Olá amigo, é compatível com cerca ECR-18 Plus, se sim, teria um how-to para configurar?

**Comment by fernac03** [comment]
Bom dia,
o protocolo disponibilizado pela  JFL  é  apenas  para  a linha de centrais  monitoradas  via  ethernet.

estas centrais  abaixo  com excessao da  Active 8 Ultra    tem controle  de eletrificador  entao o prococolo consegue monitorar  o eletrificador  pela  central.

Os modelos descritos abaixo usam esse protocolo de comunicação. 

Produto Placa Versão
Active 8 Ultra PCI-327 A partir de 6.0
Active 20 Ultra PCI-327 A partir de 6.0
Active 20 Ethernet PCI-340 A partir de 6.0
Active 20 Bus PCI-358 Todas
Active 32 Duo PCI-356 A partir de 5.0
Active 100 Bus PCI-350 Todas
Active Full 32 PCI-444 Todas
Active 20 PCI-325 Toda

**Comment by ITMPGIT** [comment]
eu instalei a placa de rede ethernet adicional e funciona via aplicativo JFL, mas no caso nao esta homologada para essa integração certo?
modelo:
https://jflalarmes.com.br/familias/ecr-18-plus/

**Comment by fernac03** [comment]
não  a integração só funciona  para as centrais  informadas  acima,    ai voce  interliga  o eletrificador  na central  e  consegue  monitora-los , pelo menos  é o que  a JFL  me disse  ainda  não testei pois  nao tenho o eletrificador.

**Comment by fernac03** [comment]
corrigido na versao v0.20
