### ISSUE TITLE
Monitoramento de zonas

### ISSUE THREAD

**Issue by jmanoelalmeida** [fernac03/JFL_ACTIVE#3]
Possuo uma central jfl active 20.

Armando e desarmando está ocorrendo bem pelo home assistant, porém não consigo receber as informações das zonas. Todas minhas zonas são com fio, teria algum modo de configuração que eu possa estar fazendo errado?

Cadastrei a zona, dei um nome dela e coloquei o tipo "door", pois é um sensor de abertura de porta. Porém sempre fica fechado.

Att,

**Comment by jmanoelalmeida** [comment]
Estou adicionando os logs, onde aparece que o tamanho do pacote é maior que 118
[Uploading home-assistant_jfl_active_2024-02-22T19-18-47.492Z.log…]()

**Comment by fernac03** [comment]
corrigido na versao v0.20
