### ISSUE TITLE
Configuraçao do envio

### ISSUE THREAD

**Issue by ffrauches** [fernac03/JFL_ACTIVE#4]
Ola,

Teria alguma documentação dos processos que deveriam ser feitos na central para o envio das informações dos sensores para a integracão do home assistant?

**Comment by fernac03** [comment]
bom dia , 

esta integração com o Home Assistant  fica aguardando a comunicação com a central , então nas configurações da central voce  deve  configurar  o report por  IP  principal  sendo o ip do home assistant  e  a  porta  deve  ser a mesma .

exemplo integração configurada  no Home Assistant  ip  :  192.168.80.1  porta :  8085   a  central deve  ser  configurada  ip de destino 1 sendo  192.178.80.1   e porta de destino 1: 8085.

na integração criar  as  zonas  da mesma  forma  que  foram criadas no programador  da JFL  
exemplo programador  zona1:  01   Integração : 01
pronto assim que  a central  se conectar no  Home  assistant  voce  podera  ver o status  das  diversas zonas e  armar desarmar

**Comment by ffrauches** [comment]
Boa noite...
Desculpe a demora em responder estive sem acesso ao HA por uns dias...
Fiz da forma como mencionado acima.... Eu tinha entendido como fazer... eu nao estava conseguindo acessar a central e encontrar o local onde configuraria as informacoes... mas resolvi isso ja...

Pelo que eu consegui monitorar no meu firewall esta tendo conexao entre os 2 porem as informacoes nao atualizam... olhei no log do HA Core e estou tendo agora esse erro abaixo:


Registrador: py.warnings
Fonte: custom_components/jfl_active/__init__.py:14
integração: JFL Active ([documentação](https://github.com/fernac03/JFL_ACTIVE), [problemas](https://github.com/fernac03/JFL_ACTIVE/issues))
Ocorreu pela primeira vez: 20:04:06 (3 ocorrências)
Último registro: 20:04:06

- /usr/local/lib/python3.12/site-packages/alarmdecoder/decoder.py:605: SyntaxWarning: invalid escape sequence '\.' matches = re.match('^!Sending(\.{1,5})done.*', data)
- /usr/local/lib/python3.12/site-packages/alarmdecoder/messages/panel_message.py:73: SyntaxWarning: invalid escape sequence '\[' _regex = re.compile('^(!KPM:){0,1}(\[[a-fA-F0-9\-]+\]),([a-fA-F0-9]+),(\[[a-fA-F0-9]+\]),(".+")$')
- /usr/local/lib/python3.12/site-packages/alarmdecoder/zonetracking.py:186: SyntaxWarning: invalid escape sequence '\d' zone_regex = re.compile('^CHECK (\d+).*$')

**Comment by fernac03** [comment]
corrigido na versao v0.20
