### ISSUE TITLE
Monitoramento das Zonas

### ISSUE THREAD

**Issue by fabiobaldoibs** [fernac03/JFL_ACTIVE#5]
Olá,  @fernac03 

Muito bacana sua integração, obrigado por disponibiliza-la para a comunidade. 

Fiz a integração recenetemente. Minha central é uma active 20 ethernet e a parte principal está funcionando perfeitamente. Arme, desarme e notificação de disparo. 

Porém eu não consegui fazer o monitoramento das zonas. A versão do firmware é 7.0. O tipo de sensor coloco sempre porta e no nome da zona já tentei algumas alternativas como "ZONE X", "ZONE 0X", "ZONA X", "ZONA 0X" e também tentei o nome amivavel conforme aparece no app, exemplo "Porta Sala". No HA o sensor fica como indisponível. No aplicativo, o monitoramento das zonas aparece normalmente,.

Se puder me ajudar, agradeço. 

Fabio

**Comment by fernac03** [comment]
bom dia, o nome  que  voce coloca na zona nao importa muito e sim o numero da zona 01,02,03 .... da mesma  forma que esta numerado na  central  se  a central esta com zona 1,2,3  voce  configura  a zona  no home assistant  com 1,2,3 
se na  central  esta com 01,02,03  voce configura  como 01,02,03

**Comment by fabiobaldoibs** [comment]
bom dia!

não tinha mencionado no comentário anterior, mas isso eu também testei. No caso, com ou sem os zeros. um exemplo é a garagem que está na zona 10, que ai não teria como estar errado.

**Comment by fernac03** [comment]
teria como me  enviar  os  logs de debug

Em qua., 3 de jul. de 2024 às 08:24, Baldo ***@***.***>
escreveu:

**Comment by fabiobaldoibs** [comment]
Gerei. 

Agora não tem ninguém em casa então as zonas estão todas fechadas. Se precisar fazer isso com as zonas abrindo e fechando e faço hoje a noite.

[home-assistant_jfl_active_2024-07-03T11-43-41.495Z.log](https://github.com/user-attachments/files/16083066/home-assistant_jfl_active_2024-07-03T11-43-41.495Z.log)

**Comment by fernac03** [comment]
voce poderia  substituir o arquivo
config\custom_components\jfl_active\sensor.py   por este em anexo
e reiniciar  a integração

Em qua., 3 de jul. de 2024 às 08:44, Baldo ***@***.***>
escreveu:

**Comment by fabiobaldoibs** [comment]
acho que bloqueou o anexo. não veio.

se quiser pode enviar para baldoibs@gmail.com

**Comment by fabiobaldoibs** [comment]
segue novo log de debug

como mencionado, agora não consigo testar. dou um feedback a noite
[home-assistant_jfl_active_2024-07-03T12-15-41.092Z.log](https://github.com/user-attachments/files/16084513/home-assistant_jfl_active_2024-07-03T12-15-41.092Z.log)

**Comment by fernac03** [comment]
corrigido na versao V0.20
