### ISSUE TITLE
VISUALIZAR STATUS DAS ZONAS

### ISSUE THREAD

**Issue by marcelomva83** [fernac03/JFL_ACTIVE#6]
BOa tarde! fiz a integração conforme orientado... coloquei o IP do meu home assistant na porta 8085 e no Ip destino da central tambem...
quando coloco os sensores dentro do home assistant já tentei como 09 ou 9 e não vai... coloco como Door, Windows e não reporta! só aparece como Fechado!

o que pode estar errado???? ajuda por favoR!
desde já agradeço

**Comment by fernac03** [comment]
bom dia,  qual  a versão e modelo  da  central  ? como está  o repórter da
central  ? está  configurado  na central  apenas  o ip  do homeaasistant ?

Em dom., 14 de jul. de 2024, 14:13, marcelomva83 ***@***.***>
escreveu:

**Comment by marcelomva83** [comment]
Boa noite! a versão da central é 6.6 modelo Active 32 DUO, reporter está apenas para o Ip do Homeassistant!
mostra que a central está carregando, mas os sensores sem fio não mostra o status, tenho de abertura nas janelas e de presença pela casa toda.. ja tentei com Zona 9 ou Zona 09 e não funciona.

**Comment by fernac03** [comment]
bom dia,
esta  com a versao da integração atualizada , poderia  me enviar os logs
de debug ?

Em seg., 15 de jul. de 2024 às 20:20, marcelomva83 ***@***.***>
escreveu:

**Comment by marcelomva83** [comment]
como é muito grande te mandei por e-mail agora o arquivo txt

**Comment by fernac03** [comment]
corrigido na versao v0.20
