### ISSUE TITLE
Compatibilidade

### ISSUE THREAD

**Issue by thiago-ac** [fernac03/JFL_ACTIVE#7]
Boa noite,
Essa integração tem compatibilidade com a central ECR 18 plus?
Não estou conseguindo configurar aqui.
Obrigado

**Comment by tayamim** [comment]
Não consegui instalar, dá o erro.
![image](https://github.com/user-attachments/assets/c825ee09-fa35-4d91-955b-5685a474bb4a)

**Comment by fernac03** [comment]
bom dia, nao tem suporte  a este  eletrificador
